### ISSUE TITLE
Hi I want to test model

### ISSUE THREAD

**Issue by zhangjiulong** [srvk/srvk-eesen-offline-transcriber#1]
Hi I want to test my own model trained with eesen, is there any suggestion?

**Comment by riebling** [comment]
If you already have models trained with eesen, then the end of the next paragraph shows where they
fit in. The location of models are configured by 2 parameters in `/vagrant/Makefile.options`: `GRAPH_DIR` and `MODEL_DIR`.

The transcriber uses the EESEN System found in this repository: [https://github.com/srvk/eesen](https://github.com/srvk/eesen)
In particular it uses the TEDLIUM experiment part of EESEN, found in [`asr_egs/tedlium/v2-30ms`](https://github.com/srvk/eesen/tree/master/asr_egs/tedlium/v2-30ms).
We provide 2 part models that are the result of running this experiment on a high-performance computer with very large RAM and a GPU. The models are the result of training on TED-LIUM data (TED talks: hundreds of hours of audio and transcriptions). The two model components are:
1. a nnet based acoustic model found in `/home/vagrant/eesen/asr_egs/tedlium/v2-30ms/exp/train_phn_l5_c320_v1s`
2. a language+grammar model in the form of a decoding graph found in `/home/vagrant/eesen/asr_egs/tedlium/v2-30ms/data/lang_phn_test` (or lang_phn_test_test_newlm)

The second of these is easiest to re-generate, or modify.
If you wish to re-use the (English) acoustic model, It is possible to build a new language model and grammar that are compatible with it. The data required to do this are a large, general English training text (example provided) and a dictionary (also provided) - or you may wish to substitute or combine with your own. See instructions here: [http://speechkitchen.org/kaldi-language-model-building/](http://speechkitchen.org/kaldi-language-model-building/).  A high performance computer is not required.

If you want to build new models for another language, you'll need audio and transcript data in a similar format to the TEDLIUM training data found here: [http://www-lium.univ-lemans.fr/en/content/ted-lium-corpus](http://www-lium.univ-lemans.fr/en/content/ted-lium-corpus). You will need to adapt the training - possibly by creating a folder that duplicates `tedlium/v2-30ms` and then modifying several scripts in the top-level script [`run_ctc_phn.sh`](https://github.com/srvk/eesen/blob/master/asr_egs/tedlium/v2-30ms/run_ctc_phn.sh) to match your audio and transcription data

```
  # simply link the db directory to here and skip this step                                                                                   
  local/tedlium_download_data.sh || exit 1;

  # Use the same data preparation script from Kaldi                                                                                           
  local/tedlium_prepare_data.sh --data-dir db/TEDLIUM_release2 || exit 1

  # Construct the phoneme-based lexicon                                                                                                       
  local/tedlium_prepare_phn_dict.sh || exit 1;
```

This top-level script performs the training experiment and trains new acoustic and language models.  If you start by checking out this GitHub project and follow this script, you can trace down to all the requirements and dependencies. In fact, I suggest trying this first in order to make sure you have everything required to produce a new model. But be warned this is a large task, and the nnet training may take days.

If you don't have a computer with very-large RAM (100 GB) and a GPU, you can run on Amazon AWS.  See the `Vagrantfile` and `aws.sh` in [http://github.com/srvk/eesen-transcriber](http://github.com/srvk/eesen-transcriber) for more information on provisioning and running eesen-transcriber in this way. (An AWS account is required, and this will cost money)

**Comment by riebling** [comment]
closing; no reply for 2 years
